from __future__ import annotations

import importlib.metadata
import sys
import tomllib
from pathlib import Path

from packaging.markers import default_environment
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name


ROOT = Path(__file__).resolve().parents[1]


def project_requirements(*, include_tests: bool) -> list[Requirement]:
    project = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))["project"]
    values = list(project["dependencies"])
    if include_tests:
        values.extend(project["optional-dependencies"]["test"])
    return [Requirement(value) for value in values]


def active(requirement: Requirement) -> bool:
    environment = default_environment()
    environment["extra"] = ""
    return requirement.marker is None or requirement.marker.evaluate(environment)


def locked_environment(*, include_tests: bool) -> list[str]:
    pending = project_requirements(include_tests=include_tests)
    locked: dict[str, str] = {}
    while pending:
        requirement = pending.pop()
        if not active(requirement):
            continue
        name = canonicalize_name(requirement.name)
        if name in locked:
            continue
        try:
            distribution = importlib.metadata.distribution(requirement.name)
        except importlib.metadata.PackageNotFoundError as error:
            raise RuntimeError(f"required package is not installed: {requirement.name}") from error
        if requirement.specifier and distribution.version not in requirement.specifier:
            raise RuntimeError(
                f"installed {requirement.name} {distribution.version} does not satisfy {requirement.specifier}"
            )
        locked[name] = distribution.version
        pending.extend(
            child
            for value in distribution.requires or []
            if active(child := Requirement(value))
        )
    return [f"{name}=={locked[name]}" for name in sorted(locked)]


def main() -> int:
    outputs = {
        ROOT / "requirements.lock": locked_environment(include_tests=False),
        ROOT / "requirements-test.lock": locked_environment(include_tests=True),
    }
    for output, requirements in outputs.items():
        lines = [
            "# Generated by scripts/lock-python.py using the supported Python runtime.",
            "# Refresh only after dependency review and run the release audit before merging.",
            *requirements,
            "",
        ]
        output.write_text("\n".join(lines), encoding="utf-8")
        print(f"wrote {output.relative_to(ROOT)} with {len(requirements)} packages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
